config/routes.rb
Rails.application.routes.draw do
    
    
    resources :products do
      collection do
        get :stats
      end
     
     member do
         get :stat
     end
    end
    
    resources :users, only: [:create]
    resources :orders, only: [:index, :new, :create, :destroy]
    resources :reviews, only: [:create]
    
    get 'register' => 'users#new', as: 'register'
    
    get 'login' => 'sessions#new', as: 'login'
    post 'login' => 'sessions#create'
    get 'logout' => 'sessions#destroy', as: 'logout'
    
    root 'home#index'
    
    

end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :user
  belongs_to :product
  
  before_save :set_quantity
  
  def set_quantity
      quantity = 1 if quantity == 0
  end
  
  
end

app/models/product.rb
class Product < ActiveRecord::Base
    
    #belongs_to :category
    
    has_many :orders
    has_many :buyers, through: :orders, source: :user
    #has_many :users, through: :orders
    
    # has_many :korisnika, through: :orders, source: :user
    has_many :reviews
    
    validates :price, numericality: true
    validates_presence_of :name, :price
    
end

app/models/review.rb
class Review < ActiveRecord::Base
    belongs_to :user
    belongs_to :product
end

app/models/user.rb
class User < ActiveRecord::Base
    
    has_secure_password
    
    has_many :orders
    has_many :products, through: :orders, source: :product
    
    has_many :reviews, dependent: :destroy
    
    validates_presence_of :username, :email
    
    def admin?
     role == 1
    end
    
    
  # scope :with_email, ->(email){ where("email = ?", email) }
  # scope :with_username, ->(username){ where("username = ?", username) }
  # scope :with_email_and_username, ->(email, username){ with_email(email).with_username(username).first }
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  def logged_in_user
      # @current_user ||= User.find(session[:user]) if session[:user]
      @current_user = find_user
      # if session[:user]
      # @current_user = User.find(session[:user])
      # end
  end
  
  helper_method :logged_in_user
  
  protected
  
  def authorize
        redirect_to login_path unless logged_in_user
  end
  
  def find_user
      if session[:user]
          User.find(session[:user])
      elsif cookies[:user]
          User.find(cookies[:user])
      end
  end
  
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    
    # before_action :authorize

    def index
    end
    
    def hello
    end
    
    def close
    end
    
    

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
    
  before_action :authorize
  
  def index
    if params[:user_id]
      @orders = Order.where(user_id: params[:user_id])
    elsif params[:product_id]
      @orders = Order.where(product_id: params[:product_id])  
    else
      @orders = Order.all
    end
  end
  
    
  def new
  @order = Order.new
  end
  
  def create
    @order = Order.new(order_params)
    # @order.user_id = loddeg_in_user.id
    @order.user = logged_in_user
  
    if @order.save
      redirect_to orders_path
    else
      render :new
    end
  end
  
  def destroy
      Order.destroy(params[:id])
      redirect_to orders_path
  end
  
  private
  
  def order_params
      params.require(:order).permit(:product_id, :quantity)
  end
  
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    
    before_action :authorize
    
    def index
    @products_count = Product.count
    
    if params[:sort]
        @products = Product.order(price: :desc)
    else
        @products = Product.all
    end
    
    respond_to do |format|
        format.html
        format.js 
        format.json { render json: @products }
        format.xml { render xml: @products }
    end
    
    end
    
    def show
        product_id = params[:id]
        @product = Product.find(product_id)
    end
    
    def new
        @product = Product.new
    end
    
    def create
        @product = Product.new(product_params)
        
        if @product.save
        redirect_to(products_path())
        else
            flash[:error] = 'Product create failed!'
            render :new
        end
        
    end
    
    def edit
        @product = Product.find(params[:id])
    end
    
    def update
    
        @product = Product.find(params[:id])
        if @product.update_attributes(product_params)
            redirect_to(product_path(@product))
        else
           flash[:error] = 'Neuspješno ažuriranje proizvoda'
           render :edit
        end
    end
    
    def destroy
        @product = Product.find(params[:id])
        product_name = @product.name
        @product.destroy
        flash[:notice] = "Uspješno ste obrisali: #{product_name}!"
        redirect_to products_path
    end
    
    def stats
    @total_products = Product.count
    end
    
    def stat
    product = Product.find(params[:id])
    @product_buyers = product.buyers.count
    end
    
    private
    
    def product_params
        params.require(:product).permit(:name, :price, :description)    
    end

    
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  before_action :authorize
    
  def create
      @review = Review.new(review_params)
      @review.user = logged_in_user
      
      @review.save
      @reviews = Review.where("product_id=?", params[:product_id]).order(created_at: :desc)
      
      respond_to do |format|
          format.js {}
      end
  end
  
  private
  
  def review_params
      params.permit(:content, :product_id)
  end
    
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    
  def new
  end

  def create
    #test = "hello debugger"
    #binding.pry
    # @user = User.find(2)
    # @user = User.find_by(email: params[:email])
    # @user = User.find_by_email(params[:email])
    # @user = User.where(email: params[:email]).first
    # @user = User.where("email = ?", params[:email]).first
    # @user = User.where("email = ? AND username = ?", params[:email], params[:username]).first
    # @user = User.where("email = ?", params[:email]).where("username = ?", params[:username]).first

    # @user = User.with_email(params[:email]).with_username(params[:username]).first
    # @user = User.with_email_and_username(params[:email], params[:username])  
      
      
    @user = User.find_by_email(params[:email])

    if @user && @user.authenticate(params[:password])
        
        if params[:remember_me]
            cookies[:user] = { value: @user.id, expires: 1.day.from_now }
        else
            session[:user] = @user.id
        end
        
        flash[:notice] = 'User authenticated :)'
        redirect_to root_path
    else
        flash[:error] = "Invalid email or password :'("
        redirect_to login_path
    end
    
  end

  def destroy
      if session[:user]
          session[:user] = nil
      else
          cookies.delete(:user)
      end
      redirect_to root_path
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    
  # before_action :authorize, except: [:new, :create]
    
  def new
    @user = User.new
  end

  def create

    @user = User.new(user_params)

    if @user.save
      flash[:notice] = 'User created successfully'
      redirect_to root_path
    else
      render :new
    end
  end
  
  def show
  
  end
  
=begin
  def index
  @users = User.all
  end
  
  def show
        user_id = params[:id]
        @user = User.find(user_id)
  end
=end
  
  private
    def user_params
      params.require(:user).permit(:username, :email, :password, :password_confirmation, :role)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

    def order_belongs_to_logged_in_user?(logged_in_user, order_user)
        # return true if logged_in_user == orders_user
        logged_in_user == order_user
    end
    

end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<div align="center">
<% unless flash[:notice].nil? %>
  <h2 align="center"><%= flash[:notice] %></h2>
<% end %>

<img src="http://www.unixstickers.com/image/data/buttons/png/rails.png" height="300" width="300"/>
</div>
<br/><br/>




</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rusmir</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  
  <link href='https://fonts.googleapis.com/css?family=Open+Sans+Condensed:300,700,300italic&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
  
</head>
<body style="background-color:#EEEEEE; padding:0; margin:0; border:0;">

<div id="meni" style="background-color:#000; text-align:right; color:#FFF !important; padding:10px;">
<div id="title" style="font-weight:bolder; font-size:19; font-weight:700; float:left;"><span style="color:#FF0000;">ROR 387</span> - First application</div>


<style>
#meni a {color:#FFF; text-decoration:none; }
#meni a:hover { color:#FF0000; }
</style>
<% if logged_in_user %>
  [ <span style="color:yellow; font-weight:bold;"><%= logged_in_user.username %></span> ] &bull;
<%= link_to "Početna", root_path %> &bull;
<%= link_to 'Proizvodi', products_path() %> &bull;
<%= link_to 'Narudžbe', orders_path() %> &bull; &bull; &bull;
<%= link_to 'Dodaj proizvod', new_product_path() %> &bull;
<%= link_to 'Nova narudžba', new_order_path() %> &bull;
 
 <%= link_to logout_path do %>
 <%= image_tag 'logout.png', size: '16x16' %>
 <% end %>
 
 <% else %>
<%= link_to "Prijava", login_path %>
&bull;
<%= link_to "Registracija", register_path %>
<% end %>
</div>

<%= yield %>

</body>
</html>

app/views/orders/index.html.erb
<div id="order" style="padding:20px;">
<h1> Lista narudžbi </h1>
<style type="text/css">
#headTable {
    background-color: #FF0000;
    color: #FFFFFF;
    font-weight: bold;
}
#restTable {
    background-color: #DEDEDE;
    color: #000;
    font-weight: normal;
}
</style>

<table width="100%" cellpadding="2" cellspacing="2">
<tr id="headTable">
<td>ID</td>
<td>Proizvod</td>
<td>Količina</td>
<td>Kupac</td>
<td>Cijena</td>
<td style="padding-right:10px; text-align:right;">Ukupno</td>
<td> X </td>
</tr>
<% @orders.each do |order| %>
<tr id="restTable">
<td><%= order.id %></td>
<td><%= link_to order.product.name, orders_path(product_id: order.product.id) %></td>
<td><%= order.quantity %></td>
<td><%= link_to order.user.username, orders_path(user_id: order.user.id) %> [<%= order.user.role %>]</td>
<td><%= order.product.price %></td>
<td style="padding-right:10px; text-align:right;"><%= order.product.price * order.quantity %></td>
<td>
<% if order_belongs_to_logged_in_user?(logged_in_user,order.user) %>
      <%= link_to 'Delete', order_path(order.id), method: :delete %></td>
    <% end %>
    </td>
</tr>

<% end %>
</div>

app/views/orders/new.html.erb
<div id="order" style="padding:20px; font-family:Tahoma;">

<h1> Nova narudžba </h1>

  <%= form_for(@order) do |form| %>
  <%= form.label :quantity %>
  <%= form.text_field :quantity %>

  <%= form.label :product %>
  <%= form.collection_select(:product_id, Product.all, :id, :name) %>

  <%= form.submit 'Buy' %>
  <% end %>

</div>

app/views/products/_products.html.erb
<% products.each do |product|%>
    <tr id="prikaz_po_cijeni">
    <td bgcolor="#FF9966"><%= product.id %></td>
    <td><%= product.price %></td>
    <td><%= product.name %></td>
    <td><%= product.description %></td>
    <td>
    <%= link_to 'Details', product_path(product) %> &bull;
    <%= link_to 'Edit', edit_product_path(product) %> &bull;
    <% if logged_in_user.admin? %>
      <%= link_to 'Delete', product_path(product), method: :delete %></td>
    <% end %>
    </tr>
    
<% end %>

app/views/products/_review_form.html.erb
<div style="padding:10px; background-color:#CECECE;">
<style type="text/css">
</style>

  <%= form_tag(reviews_path, remote: true) do  %>
  <%= label_tag 'Content' %>
  <%= text_area_tag :content, nil, rows: 4 %>
  <%= hidden_field_tag :product_id, product_id %>
  <%= submit_tag 'Add review', class: 'rusko_button' %>
  
  <% end %>
  
</div>

app/views/products/edit.html.erb
<h2> EDIT product </h2>

<%= form_for(@product) do |form| %>

<!-- new_product je prefix iz rake routes -->
    <%= form.label :name %><br/>
    <%= form.text_field :name %>
    <br/><br/>
    <%= form.label :price %><br/>
    <%= form.text_field :price %>
    <br/><br/>
    <%= form.label :description %><br/>
    <%= form.text_area :description %>
    <br/><br/>
    <%= form.submit 'Update' %>

<% end %>

app/views/products/index.html.erb
<div style="padding:20px;">

<h1> Proizvodi </h1> 
<!-- <%= link_to 'Unesi novi proizvod', new_product_path() %> -->
<% unless flash[:notice].nil? %>
    <div><%= flash[:notice] %>
<% end %>

<h2> Ukupno proizvoda: <%= @products_count %></h2>

<!-- <% if @products_count > 5 %>
    <h2>Yes</h2>
<% else %>
    <h2>No</h2>
<% end %>
-->
<!-- render partial: 'share/IMEFAJLA' -->
<!-- <%= render partial: 'shared/page_heading', locals: {text: 'Products page' } %> -->
<%= render 'shared/page_heading', text: "Na listi je trenutno #{@products_count} proizvoda." %>

<style> .tblHead { background-color:#FF0000; color: #FFFFFF; font-weight:bold; } </style>

<table cellspacing="2" cellpadding="5" width="100%">
<tr widht="5%">
<td class="tblHead">ID</td>
<td class="tblHead"><%= link_to 'Price', products_path(sort: true), remote: true %></td>
<td class="tblHead">Name</td>
<td class="tblHead">Description</td>
<td class="tblHead">Actions</td></tr>
<!-- products partial templates -->
<%= render 'products', products: @products %>

<tr><td bgcolor="#FF9933"><strong>&nbsp;</strong></td>
<td bgcolor="#FF9933"><strong>&nbsp;</strong></td>
<td bgcolor="#FF9933"><strong>&nbsp;<strong></td>
<td bgcolor="#FF9933"><strong>&nbsp;<strong></td>
<td bgcolor="#FF9933">&nbsp;</td></tr>
</table>

</div>

app/views/products/index.js.erb
$("#prikaz_po_cijeni").html("<%= j render partial: 'products', collection: @products %>");

app/views/products/new.html.erb
<div id="loginFrame" style="padding:20px;">

<h2> NEW Product </h2>

<%= form_for(@product) do |form| %>

<% unless @product.errors.empty? %>
    <ul style="border: 1px solid black; padding:10px;">
    <% @product.errors.full_messages.each do |message| %>
    <li> <%= message %></li>
    <% end %>
    </ul>
<% end %>

<!-- new_product je prefix iz rake routes -->
    <%= form.label :name %>
    <%= form.text_field :name %>
    <br/>
    <%= form.label :price %>
    <%= form.text_field :price %>
    <br/>
    <%= form.label :description %>
    <%= form.text_area :description %>
    <br/>
    <br/>
    <%= form.submit 'Dodaj proizvod' %>

<% end %>

</div>

app/views/products/show.html.erb
<div style="padding:20px;">
<h2>id: <%= @product.id %></h2>
<h2>name: <%= @product.name %></h2>
<h2>price: <%= @product.price %></h2>

<h1> Product details for Product: <%= @product.description %> </h1>

 <div style="border: 1px solid #CCCCCC"  id="reviews">
<%= render 'reviews/review', reviews: @product.reviews %>
 </div>
 
<hr> <%= render 'review_form', product_id: @product.id  %>

</div>

app/views/products/stat.html.erb
<h1> STATISTIKA </h1>
<%= render 'shared/page_heading', text: "Ukupno kupaca: #{@product_buyers}." %>

app/views/products/stats.html.erb
<h1> STATISTIKA </h1>
<%= render 'shared/page_heading', text: "Products count: #{@total_products} proizvoda." %>

app/views/reviews/_review.html.erb
 <% reviews.each do |review| %>
<p style="padding:5px; background-color:#CACACA;" id="review-<%= review.id %>">
<strong> <%= review.user.username %></strong> [<%= I18n.localize(review.created_at, format: "%d. %B %Y.") %>]: <%= review.content %> 
</p> 
 <% end %>

app/views/reviews/create.js.erb
<% if @review.persisted?  %>
    $("#reviews").html("<%= escape_javascript(render 'reviews/review', reviews: @reviews) %>");
   
<% else %>
alert ("NO!");
<% end %>

app/views/shared/_page_heading.html.erb
<h2><%= text %></h2>

app/views/users/new.html.erb
<h1>REGISTER PAGE</h1>
<br />
<style>
input {height:28px;}
</style>
<% unless @user.errors.empty? %>
    <ul style="border: 1px solid #CCC; background-color:#FFF; border-radius: 5px">
    <% @user.errors.full_messages.each do |message| %>
    <li> <%= message %></li>
    <% end %>
    </ul>
<% end %>
<br>

<%= form_for(@user) do |form| %>
<!-- new_product je prefix iz rake routes -->
    <%= form.label :username %><br/>
    <%= form.text_field :username %>
    <br/><br/>
    <%= form.label :email %><br/>
    <%= form.text_field :email %>
    <br/><br/>
    <%= form.label :password %><br/>
    <%= form.password_field :password %>
    <br/><br/>
    <%= form.label :password_confirmation %><br/>
    <%= form.password_field :password_confirmation %>
    <br/><br/>
    <%= form.submit ' Register! ' %>
<% end %>